### ISSUE TITLE
[Feature Request] Drinkable item for nutrition

### ISSUE THREAD

**Issue by cubesky** [WesCook/Nutrition#126]
Hello, 
I am currently make a modpack. I noticed that drinkable item such as potion and glass juice in vanilla minecraft and other mods can not add nutrition. This happened when I want to add a custom nutrition called 'water' (I don't want to add other mods like tough as nail) for juice in Pam's mod and cuisine mod.
Thank you for your great mod. It's balanced and customized.

**Comment by WesCook** [comment]
Hi cubesky,

Currently foods added to Nutrition must be registered as an `ItemFood`, and be identifiable by either item ID or metadata.  The vanilla potion system (which includes water bottles) uses NBT data instead of metadata.  This means that unfortunately potions cannot be differentiated by Nutrition.

For other mods like Pam's and the Cuisine mod, it all depends on how those items are registered.  Unfortunately not all foods are compatible right now.

**Comment by cubesky** [comment]
I just confirmed ~Pam's~ and Cuisine mod are contain `net.minecraft.potion.Potion`. So can I manually set a nutrition value to it?  
* Pam's use normal item but set ItemUseAction to DRINK

**Comment by WesCook** [comment]
No, it's not possible to add nutrients to potion items right now.  That might be changing in the future though.  I underestimated the number of foods in modded Minecraft that don't actually identify themselves as foods, so need to correct some original designed decisions there.

**Comment by cubesky** [comment]
Ok, thank you. This mod is so powerful!

**Comment by WesCook** [comment]
I'll mark this issue as closed for now, but best of luck in creating your modpack!
