### ISSUE TITLE
Support for the mods Sanity and Akkamadi's Ashenwheat

### ISSUE THREAD

**Issue by Xorbah** [WesCook/Nutrition#141]
https://minecraft.curseforge.com/projects/akkamaddis-ashenwheat?gameCategorySlug=mc-mods&projectID=228524

https://minecraft.curseforge.com/projects/sanity?gameCategorySlug=mc-mods&projectID=304817

**Comment by WesCook** [comment]
Thanks for your suggestions.  I've decided to add Ashenwheat as it adds some useful crops and has a large number of downloads.  Sanity however only adds one food, which I've opted not to support because it adds to my maintenance time with little payoff.

Ashenwheat will be included in the next release.

**Comment by WesCook** [comment]
[v4.2.0](https://github.com/WesCook/Nutrition/releases/tag/v4.2.0) is now out with Ashenwheat support.
