### ISSUE TITLE
1.12 Support

### ISSUE THREAD

**Issue by Ristovski** [WesCook/Nutrition#15]
Is porting to 1.12 planned as of now? Feel free to use this issue to track progress.

**Comment by WesCook** [comment]
It is planned, hopefully soon.  I've just been focusing on finishing up other projects lately.

The port itself will be very easy.  The hard part will be maintaining mod support for three different versions.

**Comment by Sunconure11** [comment]
I'd say dump 1.10.2, and work on 1.11.2 and 1.12. Though there's going to be a 1.12.1.

https://twitter.com/Dinnerbone/status/890546777157505024

**Comment by Lothrazar** [comment]
1.12 support would be awesome. if youre busy waiting on 1.12.1 makes sense too

**Comment by WesCook** [comment]
Good news, 1.12 support is [officially out](https://github.com/WesCook/Nutrition/releases/tag/v2.0.0)!

This release is marked 2.0.0 because I made some small changes to the json format.  Specifically the `detect=nutrient` option has been replaced by a more powerful whitelist system.  The included `example.json` nutrient shows the format for this.

Enjoy, and let me know if you have any questions/bugs.

**Comment by Lothrazar** [comment]
Thanks a bunch @WesCook . I think youve already answered this a ton, but is this on curseforge? And if not we can use it on curse modpacks fine I assume.  Also do you have any public social media such as twitter?

**Comment by WesCook** [comment]
It's not on CurseForge, however you're completely free to use it in your own Curse packs or elsewhere.  I did see that somebody added the mod to the non-Curse approved mod list, so you shouldn't have any trouble with it.

As for social media, you can find me on Twitter at the same name.  Mostly I've never been very good at social media though.  :)
