### ISSUE TITLE
Missing entries in default configuration

### ISSUE THREAD

**Issue by LemADEC** [WesCook/Nutrition#154]
As of Nutrition-1.12.2-4.3.0, the following items are missing in the default configuration:
- vegetables
ic2:terra_wart              (could be considered more like a fruit)

- proteins
minecraft:rotten_flesh      (is it intended to be missing?)
minecraft:spider_eye
nuclearcraft:dominos        (it's a meat pizza)
twilightforest:experiment_115    (it's a self regenerating cake, could be animal of vegetable)

- grains
botania:manacookie         (a.k.a. biscuit of totality)
enderio:item_ender_food  (a.k.a. enderios from milk, wheat & ender pearl)
nuclearcraft:dominos
xreliquary:glowing_bread

- fruit
integrateddynamics:menril_berries
mysticalagriculture:*_apple
wizardry:fairy_imbued_apple

- dairy
nuclearcraft:marshmallow        (meat makes gelatine, add sugar to make marshmallow)
enderio:item_ender_food

Also, it would be nice to have Bird's foods added, from https://minecraft.curseforge.com/projects/birds-foods

**Comment by WesCook** [comment]
Thanks for the information and suggested categories.

Most of these exclusions are because the mods don't currently have official support.  A lot of these are big mods which only add one or two foods.  I generally omit these because they add a lot to testing time, and have small payoff.

Both entries from Minecraft are intentionally skipped for balance reasons.

I do support Twilight Forest though so I will look into Experiment 115.  At the time I think I wasn't sure what it was.

**Comment by WesCook** [comment]
The Twilight Forest addition has been included in [v4.4.0](https://github.com/WesCook/Nutrition/releases/tag/v4.4.0).  The others are excluded due to lack of support, so I'll mark this issue as closed now.
