### ISSUE TITLE
TechGuns slot issue

### ISSUE THREAD

**Issue by kellixon** [WesCook/Nutrition#159]
When the food in the slot mod TechGuns, the scale not moving. Everything is always 50%

**Comment by WesCook** [comment]
Can you clarify if this is a request for adding a food from this mod, or if TechGuns adds an alternate method of eating which does not update nutrition values correctly?  Thank you.

**Comment by kellixon** [comment]
In the mod TechGuns have a slot for auto-feeding food. The character is eating, but in the GUI Nutrition nothing changes.

**Comment by WesCook** [comment]
I have no idea how I'd even approach that.  Nutrition checks when items are finished being used (`LivingEntityUseItemEvent.Finish`), then checks if it's an `ItemFood`.  If so, it adds the appropriate nutrients.

https://github.com/WesCook/Nutrition/blob/1.12/src/main/java/ca/wescook/nutrition/events/EventEatFood.java#L91-L109

TechGuns likely doesn't simulate an "item use" event for auto-feeding, so that code is never being triggered.

Peeking at the TechGuns code, it looks like the auto-feeder basically [handles everything manually](https://github.com/pWn3d1337/Techguns2/blob/e37528bad29dea96b537c4e52040bc65a3308687/src/main/java/techguns/events/TGTickHandler.java#L385-L441).  So maybe it's not as simple as triggering the event after all.

Ultimately, @pWn3d1337 would be the one to ask.  I think they're in a better position to add integration.  If that's not possible though, then unfortunately the two features will just have to be incompatible.

I'm going to close this for now as I can't add support on my end without a hack.  It's not locked though, so feel free to respond below.
