### ISSUE TITLE
[Modpack ATM3] Buffs not present all the time after joining server.

### ISSUE THREAD

**Issue by Pengukeks** [WesCook/Nutrition#171]
I had 100% on all nutrients the day I logged of. The next day when I logged in I still had 100% on all nutrients but no buff at all. 
I'm wearing full IC2 Nano Suit which seems to be the issue and no cosmetic armor. Removing armor didn't do it but removing armor and then rejoining did (maybe only rejoining would have done it on its own). Only removing the helmet doesn't do it.
(Player number 1-3; confirmed happening on 2-3; not sure if I had the buffs missing being the only one on the server. But it's not like in fixed issue #139 where it just runs out all the time on a server with 3 players.) :penguin: 
Edit: nvm about the Nano Suit? I just rejoined naked and don't have the buffs this time.

**Comment by WesCook** [comment]
Looks like ATM3 is still running Nutrition v4.0.0 which did have that bug you linked.  While the problem was exposed with three players online in testing, the nature of the bug means it could still trigger with only two players.  I'm guessing that's what's happening.

I'd like if ATM would update to the bug-fix version, but in lieu of that I can only suggest you manually update the mod.  I know that's difficult on servers because it requires all players do so, but if there's only three players it should be less of a hassle.

**Comment by Pengukeks** [comment]
Well, thats awkward. I checked the version but idk what happenend .. ALIENS.
I'm alone now and tried rejoining 9-10 times and I did got the buffs everytime.

**Comment by WesCook** [comment]
Thanks for letting me know!
