### ISSUE TITLE
Vanilla Food Pantry

### ISSUE THREAD

**Issue by Will0wPeak** [WesCook/Nutrition#179]
Thanks for adding the Raftugli Fruit, but I’ve noticed the Ugli Fruit Drink still isn’t supported, along with most of the (sample) sandwiches

**Comment by WesCook** [comment]
If the drinks and sandwiches use complex NBT, or don't inherit from ItemFood, then I'll not be able to support them.  I don't have the mod installed to check but I'd guess it's one of those reasons.

**Comment by WesCook** [comment]
I finally got around to checking this one and it seems to be implemented.

![image](https://user-images.githubusercontent.com/792101/76178640-3a92f980-6175-11ea-8c58-1542375b68e9.png)

So either support was added since this issue was opened, or you just needed to update your local nutrition folder from source.

Thanks for your report.
