### ISSUE TITLE
Fossils and Archeology support?

### ISSUE THREAD

**Issue by Wizard1976** [WesCook/Nutrition#193]
FnA adds a lot of foods. 

Edit 1: Also the bar doesnt seem to be working the way it used to, to show nutrient levels. The %number works, but the bars all seem to be stuck at 50%... very confusing at times. hard to keep track of nutrient levels visually. 

Love the mod, btw. Thank you.

**Comment by WesCook** [comment]
I missed your edit after the initial issue was posted.  I wish I'd seen it before, because that particular bug wasn't reported again for another six months.  I did finally fix it recently.

https://github.com/WesCook/Nutrition/issues/202

As for Fossils and Archeology, it does have support included by Nutrition.  Let me know if I'm missing any.
