### ISSUE TITLE
[1.12] Bottled milk support

### ISSUE THREAD

**Issue by Federsavo** [WesCook/Nutrition#215]
Mod: https://www.curseforge.com/minecraft/mc-mods/bottled-milk

Asking this because I am unable to add it manually through configs.

Admin edit: Fixed link

**Comment by WesCook** [comment]
If the item isn't working in the configs then it's probably not adding an `ItemFood`.  At the moment Nutrition doesn't support miscellaneous Item types.

I'd like to check how the mod adds the item, but unfortunately it's not open-source.  My guess though is it's probably adding milk bottles as potions, not food.  That seems most likely because there's also a thrown bottle variant of the milk bottle.

Unfortunately that means support won't be possible without coding changes.  I'm not looking to add potion support to the 1.12 branch at this time, so unfortunately support won't be possible.
