### ISSUE TITLE
Crash with ChocolateQuestRepoured entity

### ISSUE THREAD

**Issue by AdaraChristine** [WesCook/Nutrition#216]
When a player engages a ChocolateQuestRepoured  zombie or skeleton, the server/client crashes due to the entity eating or drinking a potion.

https://pastebin.com/dPJjjvZJ

UPDATE:Looking at the log closer it might have been the nutrition file on the server was not updated to the current version. Testing now

**Comment by WesCook** [comment]
Checking into it.  I spun up a test world with Chocolate Quest Repoured but couldn't reproduce the crash.

I reviewed the the relevant function and I'm correctly checking for a player entity first, so that shouldn't be happening.

https://github.com/WesCook/Nutrition/blob/1.12/src/main/java/ca/wescook/nutrition/events/EventEatFood.java#L94-L96

As you mentioned the configs should match on client and server.  However I see you're also running a version of Nutrition from 2017.  This is quite outdated and a number of bugs have been fixed since then.  Please update to the latest version and let me know if the problem still persists.

**Comment by AdaraChristine** [comment]
This can be closed. Players verified that the server was running an old version and updating to v4.6.1 fix the crash. Sorry for the false alarm.
