### ISSUE TITLE
 [Suggestion] Please add your Project on Curseforge

### ISSUE THREAD

**Issue by Silverrain2004** [WesCook/Nutrition#218]
Hello dear Wescook. I wanted to include your Mod into my Modpacks (several). But i cant use your Mod on Curseforge. Becouse everytime i want to Upload my Packs, they get Rejected, becouse of their policy.

Is it possible for you to add this Mod on Curseforge? , that would be awesome :)

**Comment by WesCook** [comment]
Hi Silverrain,

I won't be creating a project page myself for reasons explained in #172.  However, Nutrition is included in the allowed third-party modlist.  It shouldn't be getting rejected by Curse as it's been explicitly whitelisted.

There was recently a Curseforge project that reuploaded Nutrition without permission, but it has since been removed.  It's possible that is still causing issues with uploading the jar directly.

You'd need to ask Curse to fix the issue on their end.  You can link them to this issue if that helps.  Unfortunately beyond that there's nothing I can do as it's an error on their side.

Best of luck with your packs, and thanks for your interest in my mod.
