### ISSUE TITLE
Game Doesn't Recognize Crops with Nutrition Values

### ISSUE THREAD

**Issue by ModdingMadness** [WesCook/Nutrition#226]
Hi, I've recently started a modded server with the Nutrition mod in it and have come across an odd issue. 

Villagers will not accept any crops to trade, and I am unable to craft any recipes with crops, both vanilla or modded.

My theory is that the rotting mechanic is making the nbt data different from what the game normally recognizes as a plain carrot or potato, but as I'm not a mod maker, I obviously am out of my depth.
![2021-01-13_20 52 10](https://user-images.githubusercontent.com/77423986/104538762-1ba99300-55e2-11eb-9c5d-ff51e166b90a.png)

**Comment by WesCook** [comment]
I don't recognize it, but that seems possible.  Try turning on advance tooltips (F3+H), then take a new screenshot of what it shows.

I think Nutrition should just ignore extra NBT tags entirely, unless the food decay mod is actually changing the item IDs.

**Comment by ModdingMadness** [comment]
I have turned on advance tooltips.

It looks like it's actually showing the right type of crop now, but I still can't seem to get the recipes to work.

![2021-01-13_21 15 17](https://user-images.githubusercontent.com/77423986/104540133-7d6afc80-55e4-11eb-967b-3bce2e128c08.png)
![2021-01-13_21 15 15](https://user-images.githubusercontent.com/77423986/104540138-7e9c2980-55e4-11eb-92e3-2586155c38fd.png)
![2021-01-13_21 14 43](https://user-images.githubusercontent.com/77423986/104540143-80fe8380-55e4-11eb-93e9-788854328f45.png)

**Comment by WesCook** [comment]
Thanks for testing that.

I can't offer any help with the recipes not crafting, as that falls outside of Nutrition's responsibility.  I can try to offer assistance with things like broken tooltips, if caused by my mod, or if nutrition isn't being added when food is consumed.

From your first screenshot hovering over the carrot, I'm not seeing nutrients listed at all.  Assuming Nutrition is installed, and visual tooltips are enabled (as they are by default), that makes me think that this isn't a vanilla carrot.

If I'm not mistaken advanced tooltips should show the modid, but maybe that requires another mod like [Mod Name Tooltip](https://www.curseforge.com/minecraft/mc-mods/mod-name-tooltip) be installed.

It's not quite adding up yet.  Is the pack you're running custom-made?

**Comment by ModdingMadness** [comment]
Oh, no worries--if Nutrition doesn't do anything to recipes, then I'll be sure to look into the other mods running to see if they're the culprit.

I'm currently running a custom modpack with Nutrition, Pam's HarvestCraft, SereneSeasons, and FoodFunk for food type stuff. I have deactived FoodFunk, and everything seems to be working fine again!

![2021-01-13_21 56 42](https://user-images.githubusercontent.com/77423986/104543025-3d0e7d00-55ea-11eb-861b-2899ad1ab291.png)
![2021-01-13_21 52 07](https://user-images.githubusercontent.com/77423986/104542965-223c0880-55ea-11eb-8366-2986d67b5052.png)

You've my apologies for coming to the wrong mod-maker, and I hope I've not taken up too much of your time.

**Comment by WesCook** [comment]
No worries.  Thanks for reporting the issue, and best of luck in resolving it.
