### ISSUE TITLE
Tough as Nails Support?

### ISSUE THREAD

**Issue by MagmaSlime123** [WesCook/Nutrition#233]

**Comment by WesCook** [comment]
Tough as Nails adds potions rather than `ItemFood` entries, which are not supported.  There was [a fork](https://github.com/ljheidbrink/Nutrition) that supported TAN, but it's a few years out of date at this point.  It also worked on a timer-based system rather than the decay system used by Nutrition.

So unless TAN has changed its implemented of juices, I don't believe supporting it is possible at this time.  As such I'll close this issue.
