### ISSUE TITLE
Spice of Life: Carrot Edition Compat?

### ISSUE THREAD

**Issue by MagmaSlime123** [WesCook/Nutrition#235]
Pretty much does the same thing-ish as this mod but by degrading the food values the more 1 food is eaten. More foods you et, the more health you'll obtain at a certain point.

**Comment by WesCook** [comment]
What sort of compatibility are you looking for?  They're different approaches that try to solve the same problem of encouraging dietary variety.

**Comment by MagmaSlime123** [comment]
Sorry for the late response.

Anyway, eating a certain amount of foods will basically give you extra health. This could be integrated so the lower your nutrition is for all food groups, the less likely that extra health will be given.

There could be some other features, but I'm not sure.

**Comment by WesCook** [comment]
In terms of balance changes, that's best handled by the pack author.  Both SoL: Carrot and Nutrition support very configurable balance changes, and there should be enough controls to let the pack author balance things as they wish.

As far as I'm aware the mods otherwise play nicely together, so I'll close this issue as non-actionable.

**Comment by MagmaSlime123** [comment]
Oh. Well, it'd be nice if the health adding part of SoL: Carrot was compat. with this.

**Comment by WesCook** [comment]
In packs I've played, both mods work fine in junction.  They both add hearts respective of their own conditions as expected.
