### ISSUE TITLE
Permission for repost on CurseForge

### ISSUE THREAD

**Issue by Emmaker** [WesCook/Nutrition#239]
I'll start by saying that I've already reposted the mod on CurseForge. Your mod, Nutrition, has been posted to the CurseForge site already under my account. However, I've followed the license's rules, and provided multiple links back to your GitHub page, all while giving full credit to you for creating the mod. Due to all this I don't require your permission, legally at least, but it would still ease my consciousness - and probably many others - if I got direct permission from you for this repost. Please take at much time as you'd like to think it over and respond. I'm willing to take it down if that is what you really desire.

**Comment by WesCook** [comment]
Hi James,

Thank you for your request.

The mod is licensed under MIT and I accept that means I lose some control over how it is used.  However, I did make a conscious decision not to upload it to CurseForge.  I left a comment in #172 which better explains my reasons.

To add, having someone else upload the mod presents problems as I can no longer ensure the files are kept in sync, nor can I ensure the integrity of those files.  While I don't believe you would modify the files before distribution, it is always something to be aware of.

Finally, having the mod on CurseForge seems to create problems for those uploading the mod via the third-party mod list system.  The last time somebody uploaded Nutrition (and they did break the license), users were no longer able to verify their packs when my mod was included.

For these reasons I would request you remove the mod from CurseForge, in spite of the license.  I would like GitHub to remain the canonical source for downloading the mod.

Thank you.

**Comment by Emmaker** [comment]
I understand, the reasons you have brought to my attention have convinced me to pull your file from CurseForge. However, while I will remove the files, I would like to make a secondary request to keep the CurseForge **page** up. This way none of the problems presented occur, but people who utilize the CurseForge site (like me) can find the mod, and know about the Third Party mod system. Because before I uploaded the mod, I was not aware it would still be included in CurseForge modpacks without being on the site via the Third Party mod system.

**Comment by WesCook** [comment]
I can appreciate that many are invested in the CurseForge ecosystem, and that hosting a page there may increase the popularity of the mod.  However I am personally made uncomfortable by there being a second page that - at least on its surface - appears to be an official source for the mod.  I believe this creates ambiguity and results in an undesirable loss of control over the project for me.

There's ambiguity because many users will assume CurseForge is the de facto source if a page exists.  There may be a link to GitHub - even a prominent one - but users frequently skip these sorts of warnings and go straight to the downloads.  If the downloads are not included they may simply assume the mod is no longer available.

Regarding "loss of control", this may not be of concern for others but as a project maintainer, I care about the messaging and distribution of my work.  Even from the current CurseForge page I can identify problems such as the branding being wrong (it's just Nutrition, not Nutrition Mod).  Understand that I'd be giving up the ability to fix errors like these, should they exist.

So I am made uncomfortable by the page still being present.  I'd ask that you decommission it as well as remove the downloads.  Thank you.

**Comment by Emmaker** [comment]
I understand. I will take down both the page and the downloads as you request. Thank you for creating such a great mod by the way, it may just seem like I'm giving a boiler plate response but seriously, the way this spices up vanilla gameplay is actually really astonishing. Especially if it's configured well.

**Comment by Sunconure11** [comment]
https://github.com/WesCook/Nutrition/issues/240

I can't upload new builds of a curse pack with this mod as a result of this, due to it looking for an invalid ID. Did you remove the project entirely from curse yet? You need to do that, not just archive it.

@JamesTheMaker

@WesCook
