### ISSUE TITLE
scientific error

### ISSUE THREAD

**Issue by KaduChavez** [WesCook/Nutrition#243]
I installed HarvestCraft, knowing it's a compatible mod, and I came across an error in the science of nutrition, grains like soy and chickpeas are high in protein in real life, every 100 grams of chicken contains 27 grams of protein and every 100 grams of soy contains 38 grams of pure protein, while in the game beans that should be high in protein are only rich in vegetable matter, this is scientifically incorrect, the terrafirmacraft mod is scientifically correct, as it is possible to obtain proteins from vegetable sources such as soy.

**Comment by WesCook** [comment]
Both Pam's soybeans and chickpeas are included under the `listAllveggie` ore dictionary, which Nutrition uses to assign nutrients in bulk.  Even though I agree these would be better as protein sources, I generally defer to the mod author in these cases rather than try reassigning them to fit my needs.

In addition, adding protein as well as vegetable may make these items overpowered, and I generally try not to have multiple nutrients for "base crops" like that.  It is of course possible to make these edits in your own pack though.
