### ISSUE TITLE
[Suggestion] Compat.  with some Aether addons.

### ISSUE THREAD

**Issue by MagmaSlime123** [WesCook/Nutrition#249]
I know the Aether Legacy mod already has compat. but a few addons for it apparently don't.

https://www.curseforge.com/minecraft/mc-mods/aether-addon (Aether Lost Content)
https://www.curseforge.com/minecraft/mc-mods/aether-additions

Both have quite a few new bits of food. Also, some of Aether's food items have no nutrition values.

**Comment by WesCook** [comment]
At this point in the mod's life I don't think I'll be adding new mod support unless there's many requests for it.  Most 1.12 mods have been frozen at this point, and I suspect interest has begun to wane.  Besides, I've already added support for 86 mods over the years.

I'll still accept PRs for additions, and of course fix any reported bugs.  Otherwise, Nutrition is designed around customization, and modpack authors can support any mod they'd like.

So I think I'll begin closing requests for new mod support.  Comments are not locked however, so others may comment if they wish to add their support.
