### ISSUE TITLE
Custom Nutrients display name

### ISSUE THREAD

**Issue by OrdinatorStouff** [WesCook/Nutrition#25]
I have created custom nutrients but the display name is formatted like a resource location and I'm not sure if there's a way to change that. The examples and wiki don't seem to cover it. Example photos:

![image](https://user-images.githubusercontent.com/6283913/29342985-ff64934c-81e2-11e7-8dab-3beebc898682.png)

![image](https://user-images.githubusercontent.com/6283913/29342993-0904991a-81e3-11e7-8549-a2a83f855f5b.png)

Is there a way to give them a nice-looking "display name" ?

**Comment by WesCook** [comment]
Hey there,

This info is actually in the FAQ rather than the nutrients page.  That might be a better place for it, though.  I'll look into updating that.

For now though, here's the link to the FAQ answer:

https://github.com/WesCook/Nutrition/wiki/Frequently-Asked-Questions#how-do-you-add-localizations-for-nutrients

**Comment by OrdinatorStouff** [comment]
It took some trial and error with ResourceLoader to find the correct folder structure it needed to be in but I finally figured it out:

`[root minecraft directory]\resources\minecraft\lang\en_us.lang`

![image](https://user-images.githubusercontent.com/6283913/29369982-fc28ada0-8258-11e7-8689-9947a30095c2.png)

Thanks again!

**Comment by WesCook** [comment]
Glad you got it worked out!  I'd suggest using `nutrition` as the modid rather than `minecraft`, though.  It will still load the same either way, but this makes it more clear what the language file is for.  If you want to change more mods later (textures, strings, etc), this helps keeps it organized.

Also, I'll look into increasing the width of the container in the future if the text is cut off like that.  That doesn't look great as-is.

Cheers.

**Comment by OrdinatorStouff** [comment]
Yeah I was going to re-name it to fit better but was just showing off that I figured it out. I didn't know I could change the folder name from minecraft (was following a guide on resourcepacks)...

Loving the mod though it's an amazing food system. 

Cheers~

**Comment by WesCook** [comment]
Just to let you know, the text rendering issue has been addressed in [v2.3.0](https://github.com/WesCook/Nutrition/releases/tag/v2.3.0).  Long names will now grow the GUI to prevent overlapping text.
