### ISSUE TITLE
What determines nutrient order in GUI?

### ISSUE THREAD

**Issue by koendecouck** [WesCook/Nutrition#252]
I've self-defined a number of new nutrients, and I'd like them to appear in a particular order in Nutrition's GUI. Could you tell me what determines the order these appear in? It doesn't seem to go alphabetically by name or assigned color.

**Comment by WesCook** [comment]
Honestly I'm not sure.  I never put any thought into the order of nutrients.  Let's have a look at the code.

So nutrients are pulled into the GUI from the `NutrientList.getVisible()`.  That's just a regular ArrayList, so it's ordered by insertion order.  The nutrients are inserted via `DataImporter.readConfigurationDirectory()` which uses `File.listFiles()` to enumerate the list of JSON files from disk.  That method doesn't guarantee any order, so it's likely up to the filesystem.

So it could be alphabetical, or based on proximity, or inode.  It's really up to the OS and underlying filesystem.  Adding a logical sort is probably a good idea, though it's never come up as a feature request before.

So that answers your question.  As to how to change this, it would require a mod update or fork.  Nutrition is mostly in maintenance mode at this point so I'm not adding new features unless there's a large number of requests.  I can point you in the right direction if you wish to compile it yourself for a modpack though.  Or I'd probably accept a PR, if you wanted to contribute directly back to source.

I'm glad to see you're playing with the customization aspects of the mod though, and I hope you enjoy playing with the mod.
