### ISSUE TITLE
Please allow in-game configuration.

### ISSUE THREAD

**Issue by MagmaSlime123** [WesCook/Nutrition#254]
Title. Would make debugging/testing much easier, without having to restart 5000 times.

**Comment by WesCook** [comment]
I know, and it's a feature I wish I'd added when I was actively developing the mod.  Mostly because getting the Nutrition button in the GUI to be pixel-perfect is very frustrating right now.  But most packs don't end up customizing it anyway (or much else for that matter), so I'm not sure if the dev time would have been worth it.  They ended up removing the in-game config editor from Forge in a later release anyway.

Testing nutrients and effects without restarting is very possible though, and that's the primary thing that requires testing.  See the `/nutrition reload` command for that.

https://github.com/WesCook/Nutrition/wiki/Chat-Commands

**Comment by MagmaSlime123** [comment]
In-game configs are still, and been a thing.
![2022-05-15_11 09 12](https://user-images.githubusercontent.com/51277766/168485172-a0bc1af0-3482-4f64-ac13-0c914cb2f634.png)

**Comment by WesCook** [comment]
To clarify, I meant that the config system has been overhauled in newer versions of Minecraft, and Forge has not reimplemented the in-game config UI.  That doesn't affect the 1.12 branch, but it's just an observation.

While this is a feature I wanted to add at one point, I'm unfortunately not adding new features as the mod is now in maintenance mode.  I'll be fixing bugs or other errors only.  So I'm going to close this feature request now.

Thank you for the suggestion though.

**Comment by MagmaSlime123** [comment]
Ah, sorry.

Configured is a mod on newer versions, which dynamically adds config GUIs for all mods, which this could have support for.
