### ISSUE TITLE
[Suggestion] Update Animania support

### ISSUE THREAD

**Issue by Sunconure11** [WesCook/Nutrition#33]
Animania has added some new content that I am not sure would be compatible or not, such as new milk fluids. Would it be possible to add support for those?

Also, is this compatible with 1.12.2?

**Comment by WesCook** [comment]
I added support for the new Animania foods that were compatible, but that excludes cheese wheels (they're now a sort of pseudo-cake), and also the fluids.  If I remember correctly they use the Forge universal bucket now, rather than extending ItemFood as they did previously.

The newest version is targeting 1.12.2.
