### ISSUE TITLE
Spice of Life Food Container Incompatibility

### ISSUE THREAD

**Issue by Gredh** [WesCook/Nutrition#37]
Spice of Life 1.3.10
Nutrition 2.4.1

Eating foods using Spice of Life's food containers (Lunch Bag / Lunch Box) does not add any Nutrition for the player. Taking out the food from the container and eating it as is, results in the expected effect of gaining nutrition from foods. If the player only uses the food containers for eating, they are never able to gain any nutrition points

**Comment by WesCook** [comment]
Hrmm, interesting.  I'm guessing the lunchbox is probably acting as an edible food itself, so the game doesn't know what you're actually eating.  Delicious tin box.

Unfortunately, I'm guessing there's not a simple fix without tapping into their API to get the real food.  And I'd like to do a little bit of cleanup on my end before I start adding API support, just to keep code complexity down.  That's something I may look into in the future, though.

It might also be possible for Spice of Life to change how they report food being eaten, in which case it would just work automatically.  But that may be a difficult technical change on their end.

@squeek502: Any thoughts?  You've worked with Minecraft's food systems for a lot longer than I have.  Totally fair if you don't want to make any changes on your end.

**Comment by squeek502** [comment]
The Spice of Life food containers [proxy their eating to the actual item (they call `foodToEat.onItemUseFinish`)](https://github.com/squeek502/SpiceOfLife/blob/1.9.4/java/squeek/spiceoflife/items/ItemFoodContainer.java#L354), so it should be no different from regular eating.

However, in taking a look, it turns out the `LivingEntityUseItemEvent.Finish` event is called in `EntityLivingBase.onItemUseFinish` rather then `ItemStack.onItemUseFinish`, so that event is never being called for food eaten via a food container. Will fix that on my end so that the event is fired properly.

**Comment by WesCook** [comment]
Awesome, nice work.  :)

I'm going to close this on my end then.  Thanks for reporting the issue, @Gredh.

**Comment by squeek502** [comment]
Should be fixed in TSoL v1.3.11: https://github.com/squeek502/SpiceOfLife/releases/tag/v1.3.11
