### ISSUE TITLE
Default effects?

### ISSUE THREAD

**Issue by Baughn** [WesCook/Nutrition#46]
Although Nutrition comes with a good set of nutrients, there's only the one example effect provided... so, by default, the mod does almost nothing.

I think there should be a reasonable set of defaults, such that adding the mod to a game adds something to it without always needing the player to try balancing their own game. Also, given that there isn't yet, I'm interested in seeing what effects you play with yourself.

**Comment by Baughn** [comment]
Alternately it's possible that I'm *completely blind*. Um. Ignore the above.

...though I'd still be interested in seeing anything you've added to your own game, just out of curiosity!

**Comment by WesCook** [comment]
Well in a way, the default effects are actually the ones I wrote for myself.  This mod was created specifically for my pack [Homestead](https://www.atlauncher.com/pack/Homestead), and so the default nutrients were created with that in mind.

The pack itself is modeled after the mod [TerraFirmaCraft](http://terrafirmacraft.com/), so that's where the five food group system comes from.

The effects themselves are pretty simple, as it was meant more as a template than anything.  But I think most people just leave the configs as default.

**Comment by Baughn** [comment]
I imagine they would. Unless you're building a pack, it's far too much work to customize it for yourself -- and many people find it cheaty to modify the game in that manner, not having a fine sense of balance. It's easier if you're doing it for other people.

This bug might be wandering a bit, but perhaps it'd be useful to have several different 'profiles' that can be selected using a config option? I know I'm unlikely to write effects in any case, but I think I'd be less unlikely if I could do it as a PR.

Oh by the way, some of the higher-tier Pam foods contain no nutrition at all. Bug or deliberate? Should I report?

**Comment by WesCook** [comment]
Really a nutrition profile could just be a folder of nutrients/effects, so I think adding that much complexity isn't worth it.  It could be swapped in pretty easily with a filesystem operation, or possibly using a hardmode style mod that enables config switching.

Regarding high-tier Harvestcraft foods, it might be a new food item that was added since the last Nutrition update.  You could create a bug report for that and I'll look into it the next time I work on the mod.

I know Pam recently rebalanced a lot of her foods (and vanilla's), so that will have an effect on nutritional values too.  That's derived entirely from the food's "heal" value.
