### ISSUE TITLE
[Question] Multiple Category Foods

### ISSUE THREAD

**Issue by An-Sar** [WesCook/Nutrition#50]
i was going to PR some PrimalCore food additions but wanted to ask, How do you feel about food items that fit into multiple categories? ie: ovis atre milk that provides both dairy and protein.

Looking over the existing items quickly i found at least one instance of an egg based item being in two categories, but there were other items that were not, figured i would check with you before submitting anything.

**Comment by WesCook** [comment]
Multiple categories are perfectly fine.  Some of the Pam's foods are even in all five default categories (though usually require many steps to get).  There's also some inherent balancing to make super foods a bit less over-powered.

For something like milk though, it would probably make more sense to stick to just dairy.  That's how other milks are categorized right now.  Unless there's something that specifically says "This is also a protein"?

---

The other thing worth mentioning is that the food needs to be an actual ItemFood to be supported.  The milk may be implemented in another way, in which case it likely won't be compatible with Nutrition.

I say this because I recently updated the entries for all supported mods - including PrimalCore - and don't remember adding that one.  So it may just be a recently-added item, or it may be incompatible.  Just a heads up there, if it doesn't work for whatever reason.

Cheers!

**Comment by An-Sar** [comment]
cool, that's very useful information about ItemFood, i will def keep that in mind going forward.

thank you

**Comment by WesCook** [comment]
By the way, if you're interested in adding new mod support there's a couple configs that can help.  This is the main one:

https://github.com/WesCook/Nutrition/blob/1.12/src/main/java/ca/wescook/nutrition/utility/Config.java#L105

It will print a list (to the log) of any detected food items without associated nutrients.  Makes finding valid foods in new mods a lot easier.

It should also point out any foods I might have missed in PrimalCore.
