### ISSUE TITLE
Cannot add dairy nutrient to Aether Legacy skyroot milk bucket

### ISSUE THREAD

**Issue by NotAVerb** [WesCook/Nutrition#61]
Both adding `<ore:milk>` to the bucket, and adding `"aether_legacy:skyroot_bucket:4"` to the dairy json, fail to add the dairy nutrient to the skyroot milk bucket.

**Comment by WesCook** [comment]
It looks like Aether Legacy milk buckets are stored as custom items, rather than inheriting from `ItemBucketMilk`.  So unfortunately Nutrition can't understand them as a type of food.  It would take some restructuring to make that work that unfortunately isn't in the cards right now.

So thank you for the report, but I'm afraid I can't offer any solution right now.
