### ISSUE TITLE
"Death" On Server After Dropping Below 90% Nutrition

### ISSUE THREAD

**Issue by Numorphan** [WesCook/Nutrition#77]
From https://github.com/Darkosto/SevTech-Ages/issues/2048

Screenshots and more details in that issue, but how to reproduce is as follows:

1. Be on a server (unsure if SevTech Ages only or not). This does not seem to happen in singleplayer.
2. Not have "died" yet.
3. Have above 90% Nutrition in each category.
4. Have something like Hearty Stew around to keep up other categories (not sure if necessary, but I did it).
5. Have fun with Ore Excavation to blow through hunger quickly, or any other way to burn through hunger to drop below 90% in Fruits.
6. Shortly after Fruits drops at or belowish 90%, you'll lose all your gold hearts and get a You Died screen. You can just click respawn and the screen will disappear (and you'll continue where you were). Hearts will regen back, though only to the expected 7.5 hearts.

**Comment by WesCook** [comment]
Hi @Numorphan,

I'll need to test this.  But are you saying that losing only the gold hearts is resulting in your death?  I'm not sure I understand why this would also damage your red hearts, or if they're being affected at all.

This kinda sounds like a Forge desync between the client and server based on your description in step 6.  They [recently fixed a similar issue](https://github.com/MinecraftForge/MinecraftForge/issues/4824) that caused your health to not reset properly after death.  It may be worth testing this bug out in a newer Forge release.

I'm still settling in after a move so I can't address this issue right now, but I'd appreciate any followup testing you could do and I'll see if I can replicate the problem once I'm able.

Thanks!

**Comment by Numorphan** [comment]
My red hearts are not affected at all. I lose all 10 gold hearts when I should be losing 2.5, and that's when the fake death screen shows up. I want to emphasize that I'm not actually dying, I just lose extra hearts and the death screen shows up. Clicking respawn just removes the screen and I can continue doing whatever I was doing, although my character's model is stuck at a ~45 degree angle death animation.

I'll try to test this out, though I'm hoping to do it when sevtech updates to 3.0.7, which should be any day now.

**Comment by WesCook** [comment]
To test this I:

1. Created a local client and server with no other mods.
2. Joined and set all my nutrients to exactly 90%, granting the buffs.
3. Applied a hunger level 20 effect to drain all nutrients at once.

The result is that my gold hearts disappeared simultaneously, but red hearts were unaffected.

I repeated the test using the SevTech modpack.  While it didn't kill me as described, I did notice that the hearts also didn't clear properly after the nutritional effect expired.  So that's likely the same sync issue you're seeing in the "fake death" dialogue.

As for the cause, I'm not sure.  My testing environment is on a newer version of Forge so the problem may be resolved already.  Alternatively one of the other mods in the pack might be affecting syncing behavior somehow.

But as far as I can, it's not a bug specific to Nutrition.  As such I'm going to mark this as closed for now.

If you find anything else to suggest that it *is* Nutrition specifically, let me know and I'll reopen the investigation.  Thank you.

edit: hearts did > didn't clear
