### ISSUE TITLE
GUI shows wrong values

### ISSUE THREAD

**Issue by wintrmute** [WesCook/Nutrition#8]
The in-game GUI is showing the wrong values, if I increase dairy to 100% via command, the GUI shows protein at 100%.

**Comment by WesCook** [comment]
Hrmm, I haven't seen that one before.  Is this in the 1.10 or 1.11 version?  Also, does this apply to any other nutrients, or just dairy/protein?

I'm not able to reproduce this so I may need your help in isolating any variables.

**Comment by wintrmute** [comment]
I have only tried with 1.10, I should be able to provide whatever additional info you need.

**Comment by WesCook** [comment]
So just to clarify, you ran `/nutrition set dairy 100`, and it set Protein to 100% instead, right?  What happens if you run `/nutrition get dairy` immediately afterwards?

I have a theory that the serializing process may be losing the order when sending packets, but I'm not sure.

Could you also report how consistently this happens?  Does the command always fail, or does it happen randomly?

Thanks!

**Comment by wintrmute** [comment]
Using that command, it actually DOES update dairy correctly, but the GUI shows protein set to 100%. Doing a "nutrition get dairy" returns 100. Its does seem to happen every time, and always mapped wrong the same way.

**Comment by WesCook** [comment]
Okay, it sounds like my theory is right then.  The packets are sending the nutrition data from server to client, but for whatever reason they're being sent out of order for you.  I'll have to add some sanity checks there.

Thanks for the report.  I'm not able to reproduce the issue, so I might need to send you a test build when I come up with a fix to see if it works.

**Comment by wintrmute** [comment]
I've got a small test server setup for whenever you're ready with a test build.

**Comment by WesCook** [comment]
Great, thanks.  Here's a test build for 1.10.2 with a change to how multiplayer syncing works.  Can you let me know if that corrects the behavior?

I've attached it as a zip due to upload limitations, so you'll need to extract that first.

[Nutrition-1.10.2-1.2.0-dev.jar.zip](https://github.com/WesCook/Nutrition/files/1052980/Nutrition-1.10.2-1.2.0-dev.jar.zip)

**Comment by WesCook** [comment]
Hi @wintrmute, have you had a chance to try the test build yet?  I'd like to get a fix out to everybody if possible.

Thanks!

**Comment by wintrmute** [comment]
I'll be able to test this tonight, real world has been intruding this week :)

**Comment by WesCook** [comment]
[v1.3.0](https://github.com/WesCook/Nutrition/releases/tag/v1.3.0) fixes this.

I was able to set up a Linux VPS to confirm this issue.  It looks like the order of files being read is non-deterministic, which resulted in different nutrient orders between Windows and Linux.  I've made the packet be more explicit about nutrient type now which should solve the problem.

Thanks again for the report - I likely would have missed this one otherwise.
