### ISSUE TITLE
Server Performance Concern

### ISSUE THREAD

**Issue by Rsslone** [WesCook/Nutrition#96]
I was wondering if this is a concern or am I just ignorant and this isn't actually causing the lag.
https://i.imgur.com/eH7fNxV.png
Full Timings
https://timings.aikar.co/?id=0f969971af334fc69687d52930f61730

**Comment by WesCook** [comment]
Hrmm.  I can't imagine that method being a large source for lag.  When an entity is created, Nutrition will check if it's the player, and if so attach a capability.  The only way I could see that being significant is if thousands of entities were being created every tick.

https://github.com/WesCook/Nutrition/blob/1.12/src/main/java/ca/wescook/nutrition/events/EventPlayerJoinWorld.java#L19

Still, I'm not familiar with that profiling tool nor am I an expert with Forge, so I might be doing something wrong here.  I'd want to be sure that Nutrition isn't the cause of any performance problems.

Do you know what `count(2723779)` means beside the entry name?  Is that the total number of times the method has been called?  I can't imagine it being called 726 times per tick unless a ton of entities were being created every tick.

Does your server have any extreme mob farms, or lots of XP orbs being generated?

Otherwise, I'm not sure why that might be.

**Comment by Rsslone** [comment]
I believe that count is how many times it was logged in the 5 minute period. Does the mod need to check every entity thats being created if its a player? That is a little excessive even so. I will investigate a bit more on my end but I don't think we have anyone with a massive mob farm yet.

**Comment by Rsslone** [comment]
It should be stated im not a mod developer so I won't imply you're doing something wrong, I was just looking into what's causing lag on my server and this was at the top for some odd reason. Also this tool is the same thing as running /timings on bukkit, but this is the sponge version

**Comment by WesCook** [comment]
>Does the mod need to check every entity thats being created if its a player?

Yes, I'm afraid so.  That's just how Forge has you attach a capability to players.  I don't believe I can do so any more efficiently.

However, I think we're looking at the effect, not the cause.  If my understanding of your profiler is correct, then something on your server is causing `AttachCapabilitiesEvent<Entity>` to run apparently 2.7 million times in five minutes.  My guess is that's from entities being created, but it could also be caused by a bad mod interaction elsewhere.

I'd really need a full call stack to say for sure.  A tool like [VisualVM](https://visualvm.github.io/) would produce that information, if you'd be willing to do more testing.

I'd also check out your DIM687.  There's over a thousand entities listed here.  Not to mention 700+ pistons, chests, and signs.  That sounds like a mob farm to me.

I'd suggest nuking any chunk loaders in that area and run the profiler again.  See if the numbers look a little more sane.

**Comment by Rsslone** [comment]
Unfortunately the server is running on a dedicated host, I don't think there is anything I can do remotely in terms of VisualVM. DIM687 is a DimDoors dungeon dim, so that generates a bunch of pistons and redstone. I did notice that was causing alot of lag, but it wasnt a mob farm. I'll keep looking into my lag issue, thanks for teaching a pleb something new xD

I'll close this since its not actually a bug or a issue with your mod.

**Comment by WesCook** [comment]
Ha, dimensional doors.  I can see how that might look like a mob farm.

Well thank you for alerting me to the possibility of a problem.  I'll keep my eyes out for any similar reports just in any case.  Good luck addressing your server lag.  I've been a server owner too so can commiserate on that one.
